### ISSUE TITLE
1030.20.ips: The value of memory licensed on the web is not consistent with what we see in phyp

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#286] opened 2023-06-14 08:08 UTC
After successfully activating the memory, we will see the value of memory licensed on the web is not consistent with what we see in phyp.

Before activating memory:
![image002](https://github.com/ibm-openbmc/openbmc/assets/26787008/b62eefc4-2684-418c-84ed-cfd14e7299f4)
![image003](https://github.com/ibm-openbmc/openbmc/assets/26787008/ada18b8a-d732-423e-a4b3-94c3609dc8d8)

After activating memory:
![image0031](https://github.com/ibm-openbmc/openbmc/assets/26787008/c427a3f0-bdc7-41ec-9e15-458a44bc9098)
![image005](https://github.com/ibm-openbmc/openbmc/assets/26787008/acbf93c6-9cd3-475b-a647-6eeb0e38a2ba)

What is the meaning of “memory licensed” on the web and does it indicate the amount of memory that has been activated?
 If so, the value on the web is incorrect.

**Comment by ChicagoDuan** [comment] 2023-06-14 08:22
@mzipse Can you give us some help with this issue? Thanks.

**Comment by edwin-wang** [comment] 2023-06-14 14:03
I think this is target for Everest (9043) 4 sockets. Correct? @ChicagoDuan

**Comment by ChicagoDuan** [comment] 2023-06-15 00:38
> 

Yes

**Comment by mzipse** [comment] 2023-08-24 22:35
I've been able to recreate this as well with our latest drivers.  @Nikhil-Ashoka , please have @Renuka9527 take a look at this.  It appears that even though we save the setting, we are still refreshing with the prior setting.

**Comment by neslop** [comment] 2023-09-19 20:39
Trying to get this re-energized. We see the behavior of returning, for example, "2048" as GB in our JSON structure going back to BMC, and yet BMC seems to turn it into "8192" which is 4x the expected value. We have a defect open and are still trying to find an owner in BMC who can comment on this.

**Comment by mzipse** [comment] 2023-11-02 12:42
A phyp fix has been identified for this defect.  The plan is to drop this fix into FW1050.10 and FW1030.40 service packs.

One other thing to note.  I got this from Phillip Scramlin...
Another thing that could cause confusion, is the cfcuod -query permmodinfo  macro IPS was using will only show what activations amounts were manually applied to a system, it doesn't account for base enabled memory.  We have other macros that would show what memory is actually activated (base + licensed).

**Comment by mzipse** [comment] 2023-11-02 12:43
We'll keep this open until at least one of those service packs has been delivered.

**Comment by mzipse** [comment] 2024-01-18 15:20
I understand from Xujin that you are still seeing this problem.  We would like you to share more information on what you are seeing.  Here is some information we'd like you to gather....
1) Screen shot of the GUI
2) Go to https://bmc-host-name/redfish/v1/LicenseService/Licenses/PermMem and post a screen shot
3) From PHYP, please run cfdumpcodmgr and cfcuod -sp

Thanks in advance.

**Comment by ChicagoDuan** [comment] 2024-01-25 06:23
Hi @mzipse 
I can't open this link:  https://bmc-host-name/redfish/v1/LicenseService/Licenses/PermMem
We can't run "cfdumpcodmgr" command in PHYP.

Here are these screenshots:
![激活信息页面](https://github.com/ibm-openbmc/openbmc/assets/26787008/aabff193-25c3-45cc-8148-d549143c9d61)
![permMem_redfish](https://github.com/ibm-openbmc/openbmc/assets/26787008/a09a22aa-d02f-47ce-8b0d-7971c5c05389)
![phyp_command](https://github.com/ibm-openbmc/openbmc/assets/26787008/9a178622-2285-4124-9b42-7e828f8d2eb6)

**Comment by mzipse** [comment] 2024-01-25 21:28
@ChicagoDuan , sorry for not being clear.  That link by itself will not work, you need to substitute the "bmc-host-name" in the url with your systems bmc host name.  You should then see something like this....

redfish
{
"@odata.id": ["/redfish/v1/LicenseService/Licenses/PermMem"](https://rain135bmc.aus.stglabs.ibm.com/redfish/v1/LicenseService/Licenses/PermMem),
"@odata.type": "#License.v1_0_0.License",
"AuthorizationScope": "Capacity",
"ExpirationDate": "1970-01-01T00:00:00+00:00",
"Id": "PermMem",
"LicenseType": "Production",
"MaxAuthorizedDevices": 1024,
"Name": "Permanent Memory Licenses (GB)",
"SerialNumber": "A212-0040",
"Status": {
"Health": "OK",
"State": "Enabled"
}
}

**Comment by jbremer-ibm** [comment] 2024-01-25 22:56
@ChicagoDuan, I have a an additional data point I would like to collect.

Could you run "cfcuod -query permmodinfo" from the PHYP terminal? 

Additionally, you may need to try and run "cfdumpcodmgr" once more from the PHYP terminal. The terminal doesn't like it when you backspace due to a mistype, could be the reason it was not working.

**Comment by ChicagoDuan** [comment] 2024-01-29 06:36
@jbremer-ibm  
We have confirmed again that we did not use backspace when spelling “cfdumpcodmgr”.  We still unable to run the "cfdumpcodmgr". 
Here is the screenshot：

![phypinfo](https://github.com/ibm-openbmc/openbmc/assets/26787008/8fa988c5-1779-46ad-b804-bf43b330e8e4)

**Comment by jbremer-ibm** [comment] 2024-01-29 15:33
@ChicagoDuan 
Looks like everything is working as expected here. Based on 'cfcuod -query permmodinfo', the output states you have 4096 GB licensed, which is what is listed on the BMC.

**Comment by ChicagoDuan** [comment] 2024-02-20 02:13
@jbremer-ibm @mzipse 
Thanks！We tested using 1030.40 and found that the number of licensed memory displayed on the ASMI  is the actual amount of memory enabled by the machine, not the amount of memory manually activated by PHYP. For example:

1. The machine actually has 2T of memory installed, and we manually activates 4T of memory in PHYP. The ASMI  displays 2T.
2. The machine actually has 2T of memory installed, and we manually activates 1T of memory in PHYP. The ASMI  displays 1T.

Is this as expected? If so, I think this issue can be closed. Thanks

**Comment by jbremer-ibm** [comment] 2024-02-21 15:30
@ChicagoDuan 
Appreciate the clear description. That is the expected behavior. I agree that this issue can now be closed.

**Comment by mzipse** [comment] 2024-02-21 17:06
Excellent!  Closing.

**Closed by mzipse** 2024-02-21 17:06 UTC
Labels: fixed
